# Generated by Django 3.0.8 on 2020-08-26 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlenarySession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('location', models.CharField(choices=[('plenary', 'plenary')], max_length=20, verbose_name='location')),
                ('date', models.DateField(verbose_name='date')),
                ('type_session', models.CharField(choices=[('virtual', 'virtual session'), ('presential', 'presential session')], max_length=20, verbose_name='type_session')),
                ('situation_session', models.CharField(choices=[('pre_session', 'pré session'), ('started_session', 'started session'), ('started_votation', 'started votation'), ('next_topic', 'next topic'), ('closed_session', 'closed session')], max_length=20, verbose_name='situation_session')),
                ('resume', models.TextField(blank=True, default='', verbose_name='resume')),
                ('enable', models.BooleanField(default=False, verbose_name='enable')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plenary_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'plenary session',
                'verbose_name_plural': 'plenary sessions',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('state', models.CharField(choices=[('published', 'published'), ('inactive', 'inactive')], default='published', max_length=120, verbose_name='state')),
                ('content', models.TextField(blank=True, null=True, verbose_name='content')),
                ('tweet_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='tweet id')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='image')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='title')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publications', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='plenary_session.PlenarySession', verbose_name='plenary session')),
            ],
            options={
                'verbose_name': 'publication',
                'verbose_name_plural': 'publications',
            },
        ),
        migrations.CreateModel(
            name='SavedContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('content_type', models.CharField(choices=[('news', 'News'), ('tv', 'TV Câmara'), ('radio', 'Radio Câmara'), ('agency', 'Agencia Câmara')], max_length=120, verbose_name='content type')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('url', models.URLField(verbose_name='url')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_contents', to='plenary_session.PlenarySession', verbose_name='plenary session')),
            ],
            options={
                'verbose_name': 'saved content',
                'verbose_name_plural': 'saved contents',
                'unique_together': {('content_type', 'session', 'title', 'url')},
            },
        ),
        migrations.AddConstraint(
            model_name='publication',
            constraint=models.CheckConstraint(check=models.Q(models.Q(_negated=True, content__exact=''), ('tweet_id__isnull', False), models.Q(_negated=True, image__exact=''), _connector='OR'), name='not_content_tweet_image_null'),
        ),
    ]
