# Generated by Django 3.0.8 on 2020-07-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlenarySession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('plenary', 'plenary')], max_length=20)),
                ('date', models.DateField()),
                ('type_session', models.CharField(choices=[('virtual', 'virtual session'), ('presential', 'presential session')], max_length=20)),
                ('situation_session', models.CharField(choices=[('pre_session', 'pré session'), ('started_session', 'started session'), ('started_votation', 'started votation'), ('next_topic', 'next topic'), ('closed_session', 'closed session')], max_length=20)),
                ('resume', models.TextField()),
            ],
            options={
                'verbose_name': 'plenary session',
                'verbose_name_plural': 'plenary sessions',
            },
        ),
    ]
