# Generated by Django 3.0.8 on 2020-07-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile',
            field=models.CharField(choices=[('editor', 'editor')], default='editor', max_length=120),
        ),
    ]
